import React from 'react';
import {DataComponent,DataTable,EvidenceChart,Filters,MetricCard,SectionHeader,SortableItem,SortableRegion,useDataApp,useDashboardTabs} from '../../data-app-public.jsx';
import {aggregate,metrics,performance,scope,money,percent} from './revenue-data.js';
import './revenue.css';
import {AIInsights} from './AIInsights.jsx';
import {Pipeline} from './Pipeline.jsx';
import {SalesPerformance} from './SalesPerformance.jsx';
import {DataQuality} from './DataQuality.jsx';
const tabs=[{id:'overview',label:'Executive overview',filterIds:['region','product','month','rep']},{id:'pipeline',label:'Pipeline review',filterIds:['region','product','rep']},{id:'insights',label:'AI Insights',filterIds:[]},{id:'performance',label:'Sales performance',filterIds:['region','rep']},{id:'compensation',label:'Compensation',filterIds:['region','rep']},{id:'quality',label:'Data quality',filterIds:[]},{id:'project',label:'Project & methods',filterIds:[]}];
const col=(field,label,renderCell)=>({field,label,...(renderCell?{renderCell}:{})});
const mc=(field,label)=>col(field,label,money),pc=(field,label)=>col(field,label,percent);
function Stat({id,title,value,description,queryId='opportunities',sourceRows,...layoutProps}){return <SortableItem id={id} label={title} kind="metric" span={3} minSpan={2} {...layoutProps}><MetricCard id={id} queryId={queryId} title={title} value={value} description={description} sourceRows={sourceRows} displayRows={[{metric:title,value}]}/></SortableItem>;}
function Plot({id,title,rows,sourceRows,type='horizontalBar',description,queryId='opportunities',currency='USD',height=270,...layoutProps}){return <SortableItem id={id} label={title} kind="chart" span={6} minSpan={4} {...layoutProps}><EvidenceChart id={id} queryId={queryId} title={title} variant="card" rows={rows} sourceRows={sourceRows} description={description} height={height} spec={{type,x:'label',y:'amount',currency,showXAxisLabel:false,showYAxisLabel:false,startAtZero:true,stackable:false,valueDecimals:0,colors:['var(--chart-1)']}}/></SortableItem>;}
function Table({id,title,rows,sourceRows,columns,queryId='opportunities',description,...layoutProps}){return <SortableItem id={id} label={title} kind="table" span={12} minSpan={6} {...layoutProps}><DataComponent id={id} title={title} queryId={queryId} kind="table" variant="card" displayRows={rows} sourceRows={sourceRows??rows} description={description}><DataTable rows={rows} columns={columns} caption={title}/></DataComponent></SortableItem>;}
export function DashboardContent(){
 const {snapshot,queries,filters,setFilter}=useDataApp();const {activeTabId}=useDashboardTabs(tabs);const tab=tabs.find(t=>t.id===activeTabId)??tabs[0];
 const rows=scope(queries.opportunities.rows,filters,tab.filterIds),m=metrics(rows),reps=scope(queries.compensation.rows,filters,['region','rep']),perf=performance(rows,reps),q=queries.quality_summary.rows[0],issues=queries.quality.rows;
 const applicable=snapshot.filters.filter(f=>tab.filterIds.includes(f.id)),sum=key=>reps.reduce((s,r)=>s+r[key],0),won=rows.filter(r=>r.stage==='Closed Won'),open=rows.filter(r=>!r.stage.startsWith('Closed'));
 const bars=(rs,key)=>aggregate(rs,key,'amount').sort((a,b)=>b.amount-a.amount);
 return <div className="rev-page">
 <div className="rev-context"><span className="rev-sample">Public CRM sample</span><span>2017 closes · 8,800 opportunities · Maven Analytics</span><span className="rev-author">Muthyala Mahesh Kumar</span></div>
 {applicable.length>0&&<Filters sticky filters={applicable} queries={queries} values={filters} onChange={setFilter} clearLabel="Reset view"/>}
 {tab.id==='overview'&&<>
 <SortableRegion id="executive-metrics" variant="canvas" authoredRevision={1} columns={12} spacing="standard" rows={[{"id":"executive-metrics-row-1","items":["won-revenue","open-pipeline","win-rate","average-deal"],"kind":"metrics"}]}>
 <Stat kind="metric" span={3} minSpan={2} id="won-revenue" title="Won revenue" value={rows.length?money(m.revenue):'—'} description="Closed Won amount. Sales proxy; not accounting revenue." sourceRows={rows}/>
 <Stat kind="metric" span={3} minSpan={2} id="open-pipeline" title="Open opportunities" value={m.open} description="Engaging and Prospecting deals. Source has no open amounts or expected close dates." sourceRows={rows}/>
 <Stat kind="metric" span={3} minSpan={2} id="win-rate" title="Win rate" value={percent(m.winRate)} description={`${m.won} won / ${m.closed} closed deals. Open opportunities excluded.`} sourceRows={rows}/>
 <Stat kind="metric" span={3} minSpan={2} id="average-deal" title="Average won deal" value={money(m.average)} description="Won amount divided by won deal count." sourceRows={rows}/>
 </SortableRegion>
 <SectionHeader id="revenue-pipeline-heading" title="Revenue & pipeline"/>
<SortableRegion id="executive-charts" variant="canvas" authoredRevision={1} columns={12} spacing="standard" rows={[{"id":"executive-charts-row-1","items":["monthly-revenue","stage-pipeline"]},{"id":"executive-charts-row-2","items":["regional-revenue","product-revenue"]},{"id":"executive-charts-row-3","items":["opportunity-detail"]}]}>
 <Plot kind="chart" span={6} minSpan={4} id="monthly-revenue" title="Monthly won revenue" type="bar" rows={aggregate(won,'month','amount').sort((a,b)=>a.label.localeCompare(b.label))} sourceRows={won} description="Source close dates, March–December 2017; earlier months contain no closed deals."/>
 <Plot kind="chart" span={6} minSpan={4} id="stage-pipeline" title="Open opportunities by stage" currency={null} rows={aggregate(open.map(r=>({...r,count:1})),'stage','count')} sourceRows={open} description="Deal counts; open monetary values are unavailable."/>
 <Plot kind="chart" span={6} minSpan={4} id="regional-revenue" title="Won revenue by sales office" rows={bars(won,'region')} sourceRows={won}/>
 <Plot kind="chart" span={6} minSpan={4} id="product-revenue" title="Won revenue by product" rows={bars(won,'product')} sourceRows={won}/>
 <Table kind="table" span={12} minSpan={6} id="opportunity-detail" title="Opportunity explorer" rows={rows} columns={[col('opportunity_id','ID'),col('account','Account'),col('rep','Representative'),col('stage','Stage'),mc('amount','Amount'),col('close_date','Close date')]} description="Search and sort the validated records behind this view."/>
 </SortableRegion></>}
 {tab.id==='pipeline'&&<Pipeline rows={rows}/>}
 {tab.id==='insights'&&<AIInsights query={queries.insights}/>}
 {tab.id==='performance'&&<SalesPerformance m={m} reps={reps} perf={perf} rows={rows} Stat={Stat} Plot={Plot} Table={Table} col={col} mc={mc} pc={pc} money={money} percent={percent}/>}
 {tab.id==='compensation'&&<>
 <SortableRegion id="compensation-metrics" variant="canvas" authoredRevision={1} columns={12} spacing="standard" rows={[{"id":"compensation-metrics-row-1","items":["commission-total","commission-average","target-achieved","below-target"],"kind":"metrics"}]}>
 <Stat kind="metric" span={3} minSpan={2} id="commission-total" title="Estimated payout" value={money(sum('payout'))} queryId="compensation" sourceRows={reps} description="Portfolio estimate: 5% × won revenue. No accelerators or deductions."/>
 <Stat kind="metric" span={3} minSpan={2} id="commission-average" title="Average payout" value={money(reps.length?sum('payout')/reps.length:null)} queryId="compensation" sourceRows={reps}/>
 <Stat kind="metric" span={3} minSpan={2} id="target-achieved" title="At or above scenario target" value={`${reps.filter(r=>r.achievement>=1).length} / ${reps.length}`} queryId="compensation" sourceRows={reps}/>
 <Stat kind="metric" span={3} minSpan={2} id="below-target" title="Below scenario target" value={reps.filter(r=>r.achievement<1).length} queryId="compensation" sourceRows={reps}/>
 </SortableRegion>
 <SectionHeader id="commission-heading" title="Simulated commission plan"/>
<SortableRegion id="compensation-charts" variant="canvas" authoredRevision={1} columns={12} spacing="standard" rows={[{"id":"compensation-charts-row-1","items":["commission-reps","commission-policy"]},{"id":"compensation-charts-row-2","items":["commission-ledger"]}]}>
 <Plot kind="chart" span={6} minSpan={4} id="commission-reps" height={800} title="Estimated payout by representative" rows={reps.map(r=>({label:r.rep,amount:r.payout})).sort((a,b)=>b.amount-a.amount)} sourceRows={reps} queryId="compensation"/>
 <SortableItem id="commission-policy" label="Plan assumptions" kind="custom" span={6} minSpan={4}><DataComponent variant="card" id="commission-policy" queryId="compensation" title="Plan assumptions" kind="custom" sourceRows={reps} displayRows={reps}><dl className="rev-policy"><div><dt>Commission basis</dt><dd>Closed Won amount</dd></div><div><dt>Rate</dt><dd>5% flat commission</dd></div><div><dt>Scenario target</dt><dd>$500,000 per agent · 2017</dd></div><div><dt>Excluded</dt><dd>Tax, FX, clawbacks and accelerators</dd></div></dl><p className="rev-note">Simulation only. No payments are approved or issued.</p></DataComponent></SortableItem>
 <Table kind="table" span={12} minSpan={6} id="commission-ledger" title="Commission calculation ledger" rows={reps} queryId="compensation" columns={[col('rep','Representative'),mc('target','Scenario target'),mc('actual','Won revenue'),pc('achievement','Scenario attainment'),pc('commission_rate','Rate'),mc('payout','Estimated payout')]} description="5% of source won value; rate and targets are portfolio assumptions. No actual pay data supplied."/>
 </SortableRegion></>}
 {tab.id==='quality'&&<DataQuality q={q} issues={issues} Stat={Stat} Table={Table} col={col}/>}
 {tab.id==='project'&&<div className="rev-case-study"><SectionHeader id="project-heading" title="A reproducible revenue operations portfolio"/>
 <p>Built by Muthyala Mahesh Kumar to demonstrate CRM data hygiene, pipeline reporting, sales analysis, grounded operational insights and traceable commission calculations.</p>
 <div className="rev-project-grid"><article><h3>Business question</h3><p>How can a revenue team turn inconsistent CRM records into reliable reporting and auditable compensation estimates?</p><h3>Completed here</h3><p>A public CRM sample, a reproducible validation and import pipeline, an interactive dashboard, Python notebooks, executable SQL, FastAPI endpoints, evidence-backed review rules, a LangChain prompt/parser chain and KPI documentation.</p></article><article><h3>Integration status</h3><ul><li>Salesforce: field model, import files, report specifications and validation-rule templates prepared.</li><li>PostgreSQL: constrained schema, loader and queries prepared; local SQL results verified with SQLite.</li><li>Power BI: Power Query imports, DAX measures and page specifications prepared. Native PBIX creation is pending.</li><li>n8n: opportunity-update workflow, currency guard, analysis API and durable duplicate-event checks implemented. Native n8n execution and notifications are pending.</li><li>AI: rules-based findings run on this snapshot. LangChain is installed and tested with a mock model; a live LLM requires credentials.</li></ul></article></div>
 <h3>Method & limitations</h3><p>Maven Analytics provides this public-domain fictional computer-hardware CRM sample. Dollar formatting is a portfolio currency convention; the source has no currency code. Revenue means won deal value, not accounting revenue. Open values, expected close dates and creation dates are unavailable. Engagement dates support engagement-to-close analysis. $500,000 annual targets and a 5% commission rate are illustrative assumptions. Native Salesforce, PostgreSQL, Power BI, n8n and live LLM connections remain pending. The public app reads a published snapshot; the separate backend API is included in the project package.</p>
 <h3>Data source & import</h3><p><a href="https://mavenanalytics.io/data-playground/crm-sales-opportunities" target="_blank" rel="noreferrer">Maven Analytics · CRM Sales Opportunities ↗</a>. Imported 8,800 opportunities, 85 accounts, 35 sales agents and 7 products from five source CSVs. Exact source files and SHA-256 checks are in the project package. Downloaded CSV bytes came from the public ZeinabBagherifard/CRM-Sales-Opportunities data mirror; no analysis or code was copied.</p><h3>Explore the work</h3><p>Inspect a chart’s data source or export filtered records through its menu. The project package includes raw and cleaned data, exceptions, notebooks, SQL, a data dictionary, KPI definitions, and integration guides.</p>
 <div className="rev-links"><a href="https://github.com/muthyalamaheshkumar8-debug" target="_blank" rel="noreferrer">GitHub profile ↗</a><a href="https://www.linkedin.com/in/maheshkumar-muthyala-51351b270" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div>}
 </div>;
}
